### ISSUE TITLE
How to preserve state properly?

### ISSUE THREAD

**Issue by hld0** [hukusuke1007/stop_watch_timer#34]
Hi!

I have been using your package for an app, and so far it works like a charm.
I am unable though to maintain the state of the stopwatch when moving away from the page. 

Looking up strategies for maintaining state in Flutter I saw that there are multiple different strategies. I was wondering what the proper way would be to keep the last `rawTime` in the stopwatch and store it.

Apart from that, I was wondering if it would be feasible to let the timer run in the background after dismissing it?

Thanks in advance!

**Comment by hukusuke1007** [comment]
Thanks for the comment.

Please manage instances of stop_watch_timer as singletons. It works fine across pages.

**Comment by lakoliu** [comment]
Just as an example of how I did this, since it took me a while to figure out, here is my code that solved the problem. I'm not sure if it is the best way, but it works. I created a new class called StopwatchHelper:

```
import 'package:stop_watch_timer/stop_watch_timer.dart';

class StopwatchHelper {
  static final StopwatchHelper _stopwatchHelper = StopwatchHelper._internal();

  final stopWatchTimer = StopWatchTimer();

  factory StopwatchHelper() {
    return _stopwatchHelper;
  }

  StopwatchHelper._internal();
}
```

Then, in my main code, instead of 
`final _stopWatchTimer = StopWatchTimer()`
I have 
`final _stopWatchTimer = StopwatchHelper().stopWatchTimer;`

And now the timer persists between page changes. Hope this helps!

**Comment by hld0** [comment]
Wow! Thank you so much @lakoliu.

Unfortunately my Flutter knowledge does not go deep enough to evaluate if it is the best way, but after many days of research and multiple failed attempts this quite simple approach finally solved my problem 😄 .

Thanks again!

**Comment by hukusuke1007** [comment]
@lakoliu Thank you.
